US95911: Removed circuit breaker for policy decision cache
predix/acs pull request #116
Opened 2017-04-10 20:22 UTC by FrankGasparovic

Signed-off-by: Frank <frank.gasparovic@ge.com>

2017-04-10 22:51 UTC, irinaepshteyn requested changes
Done reviewing.  Please address some minor comments.

2017-04-10 22:51 UTC, irinaepshteyn commented on service/src/main/java/com/ge/predix/acs/config/PolicyEvaluationCacheConfig.java
> +                LOGGER.debug("Caching disabled");
Should we log as info that cache is disable?
LOGGER.info("Policy evaluation caching is disabled.");

2017-04-10 22:51 UTC, irinaepshteyn commented on service/src/main/java/com/ge/predix/acs/config/PolicyEvaluationCacheConfig.java
> +    public PolicyEvaluationCache cache() {
Please add a unit test to test all the permutations in configuring cache

2017-04-10 22:51 UTC, irinaepshteyn commented on service/src/main/java/com/ge/predix/acs/config/PolicyEvaluationCacheConfig.java
> +                LOGGER.debug("Redis caching enabled");
Since we are going to have several caches for various purposes now, change the message to "Redis caching enabled for policy evaluation."

2017-04-10 22:51 UTC, irinaepshteyn commented on service/src/main/java/com/ge/predix/acs/config/PolicyEvaluationCacheConfig.java
> +            LOGGER.debug("In-memory caching enabled");
Change to "In-memory caching enabled for policy evaluation."

2017-04-11 17:54 UTC, FrankGasparovic commented
Comments address and build passed https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-build-pullrequest/143/badge/icon

2017-04-11 21:52 UTC, irinaepshteyn approved these changes

2017-04-11 21:54 UTC, irinaepshteyn commented
@FrankGasparovic, @anubhavi25, please rebase the commit and merge.

2017-04-11 22:25 UTC, merged