US116816: Add Spring Cloud Sleuth
predix/acs pull request #122
Opened 2017-05-16 22:01 UTC by anubhavi25

Signed-off-by: Frank <frank.gasparovic@ge.com>

2017-05-17 16:56 UTC, FrankGasparovic requested changes

2017-05-17 16:56 UTC, FrankGasparovic commented on service/src/main/java/com/ge/predix/acs/attribute/readers/ExternalAttributeReader.java
> +    private int maxNumberOfAttributes = 1500;
Is the ":1500" necessary if we initialize the value to 1500?

2017-05-17 16:56 UTC, FrankGasparovic commented on service/src/main/java/com/ge/predix/acs/attribute/readers/ExternalAttributeReader.java
> +    private int maxSizeOfAttributesInBytes = 500000;
Same as above

2017-05-17 16:56 UTC, FrankGasparovic commented on service/src/main/resources/log4j.xml
> +                   <!--value="[Z:%X{Zone-Id} C:%X{Correlation-Id} T:%X{X-B3-TraceId} S:%X{X-B3-SpanId}] %d{YYYY-MM-dd HH:mm:ss} %p [%t] %c [%F:%L] %m%n"/>-->
I think you can remove "C:{Correlation-Id}" as we won't be using that anymore.

2017-05-17 16:56 UTC, FrankGasparovic commented on service/start-acs.sh
> +    cp "${DIR}"/target/acs-service-*-exec.jar "${DIR}"/.acs-service-copy.jar
Placeholder comment to make sure to remember to make the necessary changes to acs-ci-config branch and jenkins because of this change

2017-05-17 22:04 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/attribute/readers/ExternalAttributeReader.java
> +    private int maxNumberOfAttributes = 1500;
I believe so since if the bean is Spring managed, the `@Value` will be used with the default value after the colon, but if it's created via `new` the `@Value` will *not* be used (hence the redundant default assigned value). For a similar usage, refer to https://github.com/predix/acs/blob/US116816/service/src/main/java/com/ge/predix/acs/privilege/management/dao/GraphGenericRepository.java#L56.

2017-05-17 22:04 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/attribute/readers/ExternalAttributeReader.java
> +    private int maxSizeOfAttributesInBytes = 500000;
See comment above.

2017-05-17 22:04 UTC, anubhavi25 commented on service/src/main/resources/log4j.xml
> +                   <!--value="[Z:%X{Zone-Id} C:%X{Correlation-Id} T:%X{X-B3-TraceId} S:%X{X-B3-SpanId}] %d{YYYY-MM-dd HH:mm:ss} %p [%t] %c [%F:%L] %m%n"/>-->
Removed.

2017-05-17 22:39 UTC, FrankGasparovic approved these changes
Looks good

2017-05-17 23:18 UTC, irinaepshteyn submitted a review, later dismissed
Done reviewing.  Please address my comments.

2017-05-17 23:18 UTC, irinaepshteyn commented on pom.xml
> +                <version>4.2.0.RELEASE</version>
spring-security-web is included in spring-security-bom which is included in spring-boot-starter-parent.  We could omit the version here and rely on the latest version 4.2.2.RELEASE defined by spring-boot-starter-parent.

2017-05-17 23:18 UTC, irinaepshteyn commented on pom.xml
> +                <version>4.2.0.RELEASE</version>
Same as above.  Omit the version here and rely on the latest version 4.2.2.RELEASE defined by spring-boot-starter-parent.

2017-05-17 23:18 UTC, irinaepshteyn commented on pom.xml
> +                <version>4.2.0.RELEASE</version>
Applies to all org.springframework.security dependencies.

2017-05-17 23:18 UTC, irinaepshteyn commented on pom.xml
>          <springframework-boot.version>1.2.1.RELEASE</springframework-boot.version>
springframework.version and springframework-boot.version are not used.

2017-05-17 23:18 UTC, irinaepshteyn commented on pom.xml
>          <spring-security-oauth2.version>2.0.3.RELEASE</spring-security-oauth2.version>
spring-security-oauth2.version not used.

2017-05-17 23:18 UTC, irinaepshteyn commented on pom.xml
>          <spring-security-oauth2.version>2.0.3.RELEASE</spring-security-oauth2.version>
spring-security-jwt.version not used

2017-05-17 23:18 UTC, irinaepshteyn commented on pom.xml
>          <postgres.version>9.3-1103-jdbc4</postgres.version>
postgres.version not used

2017-05-17 23:18 UTC, irinaepshteyn commented on service/src/main/resources/log4j-dev.xml
> +            <param name="ConversionPattern" value="[Z:%X{Zone-Id} T:%X{X-B3-TraceId} S:%X{X-B3-SpanId}] %d{YYYY-MM-dd HH:mm:ss} %p [%t] %c [%F:%L] %m%n"/>
Should we use com.ge.predix.log4j1.PredixLayout here?

2017-05-17 23:18 UTC, irinaepshteyn commented on service/start-acs.sh
> +                shift
Why would we want to disable predix log layout?

2017-05-18 00:01 UTC, anubhavi25 commented on pom.xml
>          <springframework-boot.version>1.2.1.RELEASE</springframework-boot.version>
Removed.

2017-05-18 00:01 UTC, anubhavi25 commented on pom.xml
>          <spring-security-oauth2.version>2.0.3.RELEASE</spring-security-oauth2.version>
Removed.

2017-05-18 00:01 UTC, anubhavi25 commented on pom.xml
>          <postgres.version>9.3-1103-jdbc4</postgres.version>
Removed.

2017-05-18 00:01 UTC, anubhavi25 commented on pom.xml
> +                <version>4.2.0.RELEASE</version>
This dependency along with all other Spring-Security-related ones here have been removed.

2017-05-18 00:02 UTC, anubhavi25 commented on pom.xml
> +                <version>4.2.0.RELEASE</version>
See comment above.

2017-05-18 00:02 UTC, anubhavi25 commented on service/src/main/resources/log4j-dev.xml
> +            <param name="ConversionPattern" value="[Z:%X{Zone-Id} T:%X{X-B3-TraceId} S:%X{X-B3-SpanId}] %d{YYYY-MM-dd HH:mm:ss} %p [%t] %c [%F:%L] %m%n"/>
This is the development XML that uses the original layout plus Sleuth-related headers and is enabled using the `human-readable-logging` flag to ACS start scripts (so it's easier to see stack traces).

2017-05-18 00:04 UTC, anubhavi25 commented on service/start-acs.sh
> +                shift
This flag swaps `PredixLayout` for the original log4j layout to provide more human-readable logs in the locally-spun-up ACS service (useful for debugging). To make this more clear, I've renamed it to `human-readable-logging`.

2017-05-18 14:15 UTC, anubhavi25 commented
[Builds #605-608 Passing (`predix-cloud*` test failures are not related to this PR)](https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-integration-pullrequest/)

2017-05-18 16:02 UTC, merged