US128553: Migrate to postgres2.0 and aws-redis for int tests
predix/acs pull request #124
Opened 2017-05-31 04:45 UTC by FrankGasparovic

2017-05-31 05:36 UTC, FrankGasparovic commented
Cloud titan int tests: https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-integration-pullrequest/611/badge/icon

Metering failed as usual but also connectorIT failed. Not sure if maybe asset was acting up or one of my changes caused it.

2017-05-31 22:05 UTC, anubhavi25 requested changes
As discussed, we should also add logic to flush the bound cache and drop/create the bound database before commencing integration tests.

2017-05-31 22:05 UTC, anubhavi25 commented on acs-integration-tests/src/test/java/com/ge/predix/acs/cloudfoundry/PushAcsApplication.java
> +        CloudFoundryService postgresService = new CloudFoundryService("dedicated-20.1", this.acsDbServiceName,
Use `dedicated-10.1` and downgrade the plans for `acs-rds-postgres-ci-{0..5}` to `dedicated-10.1` as well if they were provisioned with the higher plan.

2017-05-31 22:05 UTC, anubhavi25 commented on acs-integration-tests/src/test/java/com/ge/predix/acs/cloudfoundry/PushAcsApplication.java
> +    public String getAcsRedisServiceName() {
Can this function be made package-private?

2017-05-31 22:05 UTC, anubhavi25 commented on acs-integration-tests/src/test/java/com/ge/predix/acs/cloudfoundry/PushAcsApplication.java
> +    public String getAcsDbServiceName() {
Can this function be made package-private?

2017-05-31 22:05 UTC, anubhavi25 commented on acs-integration-tests/src/test/java/com/ge/predix/cloudfoundry/client/CloudFoundryApplicationHelper.java
> +                        .name(instance).build()).block().getApplications().size() == 0) {
Use `isEmpty()`

2017-05-31 22:05 UTC, anubhavi25 commented on acs-integration-tests/src/test/java/com/ge/predix/cloudfoundry/client/CloudFoundryApplicationHelper.java
> +                LOGGER.info(String.format("Instance '%s' does not exist", instance), e);
Use built-in formatter: `LOGGER.info("Instance '{}' does not exist", instance, e);`

2017-05-31 22:28 UTC, FrankGasparovic commented on acs-integration-tests/src/test/java/com/ge/predix/cloudfoundry/client/CloudFoundryApplicationHelper.java
> +                LOGGER.info(String.format("Instance '%s' does not exist", instance), e);
I don't think info has a signature with params and throwable 
https://www.slf4j.org/apidocs/org/slf4j/Logger.html

2017-05-31 22:29 UTC, FrankGasparovic commented on acs-integration-tests/src/test/java/com/ge/predix/cloudfoundry/client/CloudFoundryApplicationHelper.java
> +                        .name(instance).build()).block().getApplications().size() == 0) {
Fixed

2017-05-31 22:29 UTC, FrankGasparovic commented on acs-integration-tests/src/test/java/com/ge/predix/acs/cloudfoundry/PushAcsApplication.java
> +    public String getAcsDbServiceName() {
Fixed

2017-05-31 22:30 UTC, FrankGasparovic commented on acs-integration-tests/src/test/java/com/ge/predix/acs/cloudfoundry/PushAcsApplication.java
> +    public String getAcsRedisServiceName() {
Fixed

2017-05-31 22:32 UTC, FrankGasparovic commented on acs-integration-tests/src/test/java/com/ge/predix/acs/cloudfoundry/PushAcsApplication.java
> +        CloudFoundryService postgresService = new CloudFoundryService("dedicated-20.1", this.acsDbServiceName,
Fixed

2017-06-02 17:49 UTC, anubhavi25 approved these changes

2017-06-02 18:47 UTC, anubhavi25 commented
[Builds #616-617,619-620 Passing (`predix-cloud*` test failures are not related to this PR)](https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-integration-pullrequest/)

2017-06-02 21:39 UTC, FrankGasparovic commented
Looks good

2017-06-02 23:08 UTC, merged