US140969: Modify ACS graph repositories to use TinkerPop3 GraphTraversalSource instead of Graph object
predix/acs pull request #133
Opened 2017-06-30 21:26 UTC by FrankGasparovic

Signed-off-by: Chris <chris.ruppelt@ge.com>

2017-06-30 22:45 UTC, anurag-gujral reviewed
Let us discuss this next week and then we will go from there , on whether we need to call commit and rollback at all the places it is presently being called.

2017-06-30 22:45 UTC, anurag-gujral commented on service/src/main/java/com/ge/predix/acs/privilege/management/dao/GraphGenericRepository.java
> +            this.graphTraversal.tx().commit();
Since we are doing a findAll and not modifying the graph I am not sure we need to call this.graphTraversal.tx().commit();

2017-07-05 17:36 UTC, Cruppelt commented on service/src/main/java/com/ge/predix/acs/privilege/management/dao/GraphGenericRepository.java
> +            this.graphTraversal.tx().commit();
I spoke with Sanjeev and Anubhav, and they want to keep it for now for historical reasons.

2017-07-05 18:13 UTC, anubhavi25 requested changes

2017-07-05 18:13 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/privilege/management/dao/GraphGenericRepository.java
>          try {
This try-catch template:
```
try {
    ...
    this.graphTraversal.tx().commit();
} catch (Exception e) {
    this.graphTraversal.tx().rollback();
    throw e;
}
```
is used in so many places that it's worth refactoring it out into a function and using that everywhere instead, something like so:
```
private void commitTransaction(final Runnable graphQuery) {
    try {
        graphQuery.run();
        this.graphTraversal.tx().commit();
    } catch (final Exception e) {
        this.graphTraversal.tx().rollback();
        throw e;
    }
}
```
and using it with a lambda like so:
```
this.commitTransaction(() -> this.graphTraversal.<some_function>);
```

2017-07-05 18:13 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/privilege/management/dao/GraphResourceRepositoryTest.java
> +        graph.traversal().V().drop().iterate();
Would the following not work?

```
this.graphTraversalSource = graph.traversal();
this.dropAllResources();
```

2017-07-05 18:18 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/privilege/management/dao/GraphGenericRepository.java
> +            this.graphTraversal.tx().commit();
@anurag-gujral: @sanjeevchopra mentioned that there might be nuances to the calls in the `try` block that warrant committing the transaction. In a future story, we can investigate removing the `finally` blocks everywhere this pattern occurs and ensure concurrency-specific tests pass.

2017-07-05 23:38 UTC, anubhavi25 approved these changes

2017-07-05 23:43 UTC, Cruppelt commented
@anurag-gujral We believe we need the commits and rollbacks. Documentation: http://tinkerpop.apache.org/docs/3.2.3/reference/#transactions
http://s3.thinkaurelius.com/docs/titan/1.0.0/tx.html

2017-07-05 23:48 UTC, merged