DE38655: Intermittent failure in GraphResourceRepositoryTest#testUpdateAttachedEntity
predix/acs pull request #140
Opened 2017-07-20 19:15 UTC by FrankGasparovic

2017-07-21 19:04 UTC, anubhavi25 requested changes
@FrankGasparovic if you worked on this with @VoollaSandeepKumar , amend the commit with `git duet-commit` to add the sign off line

2017-07-21 19:04 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/privilege/management/dao/GraphResourceRepositoryTest.java
> +    static void deleteTwoLevelEntityAndParents(ZonableEntity e, final ZoneEntity zone,
All parameters should be `final`. Also introduce generics into the method signature to allow you to remove the `unchecked` warning:

```
static <E extends ZonableEntity> void deleteTwoLevelEntityAndParents(final E zonableEntity, final ZoneEntity zone, final GraphGenericRepository<E> repository) {
    ...
}
```

2017-07-21 19:04 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/privilege/management/dao/GraphResourceRepositoryTest.java
> +    private static void deleteThreeLevelEntityAndParents(ZonableEntity e, ZoneEntity zone,
All parameters should be `final`. Also introduce generics into the method signature to allow you to remove the `unchecked` warning:

```
private static <E extends ZonableEntity> void deleteThreeLevelEntityAndParents(final E zonableEntity, final ZoneEntity zone, final GraphGenericRepository<E> repository) {
    ...
}
```

2017-07-21 19:04 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/privilege/management/dao/GraphSubjectRepositoryTest.java
> +
Remove empty line

2017-07-21 19:04 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/privilege/management/dao/GraphSubjectRepositoryTest.java
> +
Remove empty line

2017-07-21 19:04 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/privilege/management/dao/GraphSubjectRepositoryTest.java
> +
Remove empty line

2017-07-21 19:04 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/privilege/management/dao/GraphSubjectRepositoryTest.java
> +
Remove empty line

2017-07-21 20:28 UTC, FrankGasparovic commented on service/src/test/java/com/ge/predix/acs/privilege/management/dao/GraphSubjectRepositoryTest.java
> +
Fixed

2017-07-21 20:28 UTC, FrankGasparovic commented on service/src/test/java/com/ge/predix/acs/privilege/management/dao/GraphSubjectRepositoryTest.java
> +
Fixed

2017-07-21 20:28 UTC, FrankGasparovic commented on service/src/test/java/com/ge/predix/acs/privilege/management/dao/GraphSubjectRepositoryTest.java
> +
Fixed

2017-07-21 20:28 UTC, FrankGasparovic commented on service/src/test/java/com/ge/predix/acs/privilege/management/dao/GraphSubjectRepositoryTest.java
> +
Fixed

2017-07-21 20:32 UTC, FrankGasparovic commented on service/src/test/java/com/ge/predix/acs/privilege/management/dao/GraphResourceRepositoryTest.java
> +    private static void deleteThreeLevelEntityAndParents(ZonableEntity e, ZoneEntity zone,
Fixed

2017-07-21 20:32 UTC, FrankGasparovic commented on service/src/test/java/com/ge/predix/acs/privilege/management/dao/GraphResourceRepositoryTest.java
> +    static void deleteTwoLevelEntityAndParents(ZonableEntity e, final ZoneEntity zone,
Fixed

2017-07-23 17:33 UTC, anubhavi25 commented
[Successful builds: #782-784,786](https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-integration-pullrequest/)

2017-07-23 17:33 UTC, anubhavi25 approved these changes

2017-07-23 17:33 UTC, merged