Changing policy does not invalidate ACS decision cache when connector is configured
predix/acs pull request #149
Opened 2017-08-10 23:55 UTC by FrankGasparovic

2017-08-11 00:10 UTC, FrankGasparovic commented
Build Success: https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-build-pullrequest/247/badge/icon

2017-08-11 20:13 UTC, irinaepshteyn requested changes
Done reviewing.  Please review my comments.  Let me know if you would like me to make these changes and merge.

2017-08-11 20:13 UTC, irinaepshteyn commented on service/src/test/java/com/ge/predix/acs/policy/evaluation/cache/AbstractPolicyEvaluationCacheTest.java
>          spiedCache.get(key);
@FrankGasparovic, need to validate if get() correctly returned a cached result or null.

2017-08-11 20:13 UTC, irinaepshteyn commented on service/src/test/java/com/ge/predix/acs/policy/evaluation/cache/AbstractPolicyEvaluationCacheTest.java
>          spiedCache.get(key);
@FrankGasparovic, also connectorsNotConfigured() test case should return:

new Object[] { null, null, DateTime.now(), false };

2017-08-14 15:35 UTC, anubhavi25 requested changes

2017-08-14 15:35 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/policy/evaluation/cache/AbstractPolicyEvaluationCacheTest.java
> +        result.setResolvedResourceUris(new HashSet<>(Collections.singletonList(XFILES_ID)));
Use `Collections.singleton(..)` instead of `new HashSet<>(Collections.singletonList(..))`

2017-08-14 15:35 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/policy/evaluation/cache/AbstractPolicyEvaluationCacheTest.java
> +        this.cache.resetForSubjectsByIds(ZONE_NAME, new HashSet<>(Collections.singletonList(AGENT_MULDER)));
Use `Collections.singleton(..)` instead of `new HashSet<>(Collections.singletonList(..))`

2017-08-14 15:35 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/policy/evaluation/cache/AbstractPolicyEvaluationCacheTest.java
> +        this.cache.resetForResourcesByIds(ZONE_NAME, new HashSet<>(Collections.singletonList(XFILES_ID)));
Use `Collections.singleton(..)` instead of `new HashSet<>(Collections.singletonList(..))`

2017-08-15 21:02 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/policy/evaluation/cache/AbstractPolicyEvaluationCacheTest.java
>          AttributeConnector resourceConnector = new AttributeConnector();
Remove this statement and the one below since they're unused

2017-08-16 17:49 UTC, anubhavi25 approved these changes

2017-08-16 17:50 UTC, merged