Us162430
predix/acs pull request #152
Opened 2017-08-23 00:27 UTC by sebastiantb

this is the interface for the batch api

2017-08-23 17:04 UTC, sanjeevchopra reviewed
* please bump maven minor version

2017-08-23 17:04 UTC, sanjeevchopra commented on model/src/main/java/com/ge/predix/acs/rest/PolicyEvaluationBatchRequestV2.java
> +public class PolicyEvaluationBatchRequestV2 {
BatchPolicyEvaluationRequest  or PolicyEvaluationRequestV2 ?

2017-08-23 17:04 UTC, sanjeevchopra commented on model/src/main/java/com/ge/predix/acs/rest/PolicyEvaluationBatchRequestV2.java
> +@ApiModel(description = "Policy evaluation request for V2.")
These are user docs - please describe what this version introduces.

2017-08-23 17:04 UTC, sanjeevchopra commented on model/src/main/java/com/ge/predix/acs/rest/PolicyEvaluationBatchResultV2.java
> +public class PolicyEvaluationBatchResultV2 {
PolicyEvaluationResultV2

2017-08-23 17:04 UTC, sanjeevchopra commented on model/src/main/java/com/ge/predix/acs/rest/PolicyEvaluationBatchResultV2.java
> +package com.ge.predix.acs.rest;
lets use a different package for v2

2017-08-23 17:04 UTC, sanjeevchopra commented on model/src/main/java/com/ge/predix/acs/rest/ResourceEvaluationResult.java
> +@ApiModel(description = "Resource evaluation result")
really? :)

2017-08-23 17:04 UTC, sanjeevchopra commented on model/src/main/java/com/ge/predix/acs/rest/ResourceEvaluationResult.java
> +    public Set<String> getResolvedResourceUris() {
this should return a single URI?  see my email yesterday

2017-08-23 17:04 UTC, sanjeevchopra commented on model/src/main/java/com/ge/predix/acs/rest/ResourceRequest.java
> +public class ResourceRequest {
Is RequestedResource a better name?  to avoid confusion that this is a HTTP request payload.

2017-08-23 17:04 UTC, sanjeevchopra commented on model/src/main/java/com/ge/predix/acs/rest/ResourceRequest.java
> +    public String getAction() {
Define this as a Set<String> but only allow one member initially. To avoid API change.

2017-08-23 17:08 UTC, sanjeevchopra commented on model/src/main/java/com/ge/predix/acs/rest/ResourceEvaluationResult.java
> +public class ResourceEvaluationResult {
RequestedResourceResult ?

2017-08-24 16:06 UTC, anubhavi25 requested changes

2017-08-24 16:06 UTC, anubhavi25 commented on model/src/main/java/com/ge/predix/acs/rest/ResourceEvaluationResult.java
> +    public Set<String> getResolvedResourceUris() {
@sanjeevchopra if we'll ever have more than one `resolvedResourceUri` in the future (and for backwards-compatibility), shouldn't we keep this as a `Set` that, for now, will just contain a single `String`?

2017-08-24 16:06 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/service/policy/evaluation/PolicyEvaluationBatchController.java
> +public class PolicyEvaluationBatchController {
Couple things:
- Add the `@RestController` meta-annotation which makes it clear that this is a controller implementing Spring-MVC-related methods and automatically tacks on `@ResponseBody` to all methods annotated with `@RequestMapping`
- Rename to `PolicyEvaluationControllerV2` to be consistent with the rest of your guys' naming convention and to allow implementing other  HTTP methods for `/v2/policy-evaluation` in this same class

2017-08-24 16:06 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/service/policy/evaluation/PolicyEvaluationBatchController.java
> +    @ResponseBody
Not necessary if the class is annotated with `@RestController`

2017-08-24 16:45 UTC, sanjeevchopra commented on model/src/main/java/com/ge/predix/acs/rest/ResourceEvaluationResult.java
> +    public Set<String> getResolvedResourceUris() {
I can't think of any reason. Can anyone else?  Also, while we are adding a new version of this API, I wonder if its useful to have other info about which policy matched for this evaluation - maybe just the policy name(if defined). resolvedResourceUri would belong in that `section` too.   something like..
````json
   resources: [ 
       {
           requestedResource: ""
           matchedPolicy: {
                name: "",
                resolvedResourceUri: ""
           } 
       },
]
````

2017-08-24 17:56 UTC, anubhavi25 commented on model/src/main/java/com/ge/predix/acs/rest/ResourceEvaluationResult.java
> +    public Set<String> getResolvedResourceUris() {
I agree that would be useful

2017-12-08 18:46 UTC, sanjeevchopra commented
Whats the status of this PR? If we are not working on this, please close the PR.

2017-12-08 18:50 UTC, sebastiantb commented
It is shelved for now!

2017-12-08 18:50 UTC, closed without merging