Us179127 1
predix/acs pull request #163
Opened 2017-10-06 22:43 UTC by sebastiantb

Small fix on content type in order to be able to serialize the incoming result of the audit service

2017-10-06 23:26 UTC, anubhavi25 requested changes
Minor change requested. Also please put the passing pull request integration job URLs after running the pull request pipeline.

2017-10-06 23:26 UTC, anubhavi25 commented on acs-integration-tests/src/test/java/com/ge/predix/integration/test/PredixAuditIT.java
> +        headers.setAccept(Arrays.asList(MediaType.APPLICATION_JSON));
Use `Collections.singletonList` instead

2017-10-07 00:16 UTC, sebastiantb commented
https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-build-pullrequest/283/
https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-integration-pullrequest/952/
https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-integration-pullrequest/953/
https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-integration-pullrequest/950/
https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-integration-pullrequest/949/

2017-10-09 17:53 UTC, anubhavi25 approved these changes

2017-10-09 17:53 UTC, merged