US193682: ACS: Refactor integration tests listeners and grouping to remove dependency on cloud foundry packages
predix/acs pull request #178
Opened 2017-11-01 18:13 UTC by VoollaSandeepKumar

US193682: ACS: Refactor integration tests listeners and grouping to remove dependency on cloud foundry packages

2017-11-02 00:07 UTC, irinaepshteyn requested changes
Done reviewing.  Please address my comments.

2017-11-02 00:07 UTC, irinaepshteyn commented on acs-integration-tests/src/test/java/com/ge/predix/test/TestNameLogger.java
> +    public enum TestStatus {
protected or package access level should be enough.

2017-11-02 00:07 UTC, irinaepshteyn commented on acs-integration-tests/src/test/java/com/ge/predix/test/TestNameLogger.java
> +    public static void logInvocation(final TestStatus testStatus, final IInvokedMethod method) {
protected or package access level should be enough.

2017-11-02 00:07 UTC, irinaepshteyn commented on acs-integration-tests/src/test/resources/log4j.xml
> +
Should we turn on DEBUG for the TestNameLogger base class as well?

2017-11-02 00:07 UTC, irinaepshteyn commented on acs-integration-tests/src/test/java/com/ge/predix/test/TestNamePredixLogger.java
> +        logInvocation(TestStatus.STARTING, method);
We could call super here to do the logging.

2017-11-02 00:07 UTC, irinaepshteyn commented on acs-integration-tests/src/test/java/com/ge/predix/test/TestNamePredixLogger.java
> +                method);
We could call super here to do the logging.

2017-11-02 00:07 UTC, irinaepshteyn commented on acs-integration-tests/src/test/java/com/ge/predix/test/TestNamePredixLogger.java
> +package com.ge.predix.test;
Add licensing header.

2017-11-02 23:13 UTC, VoollaSandeepKumar reviewed
Fixed

2017-11-02 23:13 UTC, VoollaSandeepKumar commented on acs-integration-tests/src/test/java/com/ge/predix/test/TestNameLogger.java
> +    public enum TestStatus {
Changed to Protected

2017-11-02 23:13 UTC, VoollaSandeepKumar commented on acs-integration-tests/src/test/java/com/ge/predix/test/TestNameLogger.java
> +    public static void logInvocation(final TestStatus testStatus, final IInvokedMethod method) {
Changed to Protected

2017-11-02 23:13 UTC, VoollaSandeepKumar commented on acs-integration-tests/src/test/java/com/ge/predix/test/TestNamePredixLogger.java
> +package com.ge.predix.test;
Fixed

2017-11-02 23:13 UTC, VoollaSandeepKumar commented on acs-integration-tests/src/test/resources/log4j.xml
> +
I think its already added

2017-11-04 00:26 UTC, irinaepshteyn approved these changes
Approve.  Please squash commits and merge.

2017-11-04 00:29 UTC, merged