Removed predix specific functionality and tests
predix/acs pull request #182
Opened 2017-11-13 19:56 UTC by irinaepshteyn

- Removed predix maven profiles and service startup scripts;
- Removed predix dependencies and cloud configurations;
- Removed ZAC monitoring, predix audit, metering, and dynamic log configurer;
- Removed dependency on cloud foundry utilities for testing;
- Removed predix specific integration tests;

2017-11-13 22:16 UTC, sanjeevchopra commented
@anubhavi25 - please review this PR.  I wont get to this today.

2017-11-14 20:10 UTC, anubhavi25 requested changes
Sans some minor issues, looks good for the most part 👍

2017-11-14 20:10 UTC, anubhavi25 commented on README.md
> +mvn clean install [-P "public-titan" -s <maven_settings_file>]
I think you meant `[-P public-titan] [-s <maven_settings_file>]` otherwise what is being said is that both options are optional *only when specified together* instead of individually

2017-11-14 20:10 UTC, anubhavi25 commented on acs-integration-tests/pom.xml
>              <build>
Some common `configuration` parameters like `argLine`, `skipTests`, and `parallel` can be pulled up. However, child modules in the `predix-master` branch that run Predix-related integration tests might be included in the `<modules>` section of this POM, in which case they might erroneously inherit common configuration properties that don't pertain to them.

Here's a sample hierarchy that we might have in the future demonstrating why this might cause an issue:
```
acs-integration-tests/pom.xml
|- predix-local/pom.xml
|- predix-local-titan/pom.xml
|- predix-cloud/pom.xml
|- predix-cloud-titan/pom.xml
```

2017-11-15 23:51 UTC, irinaepshteyn commented
@anubhavi25, addressed PR comments.  As to integration tests pom refactoring, I created a separate story to consider creating modules for each test profile.

2017-11-16 01:04 UTC, anubhavi25 approved these changes

2017-11-16 01:04 UTC, merged