Added index for version vertex
predix/acs pull request #47
Opened 2016-09-23 21:41 UTC by bsekar

Signed-off-by: Sanjeev <sanjeev.chopra@ge.com>

2016-09-23 21:42 UTC, bsekar commented
http://predix1.jenkins.build.ge.com/job/Predix-Security/job/acs-build-n-test-pullrequest/659/

2016-09-27 02:34 UTC, sanjeevchopra commented
@amiri-ge  please review .
- PR checks passed - http://sjc1jenkins08.crd.ge.com:8080/job/Predix-Security/job/acs-build-n-test-pullrequest/663/console
- Siva verified performance tests on this branch as well

2016-09-27 18:23 UTC, sanjeevchopra commented
@irinaepshteyn   , please review. (Dario is out)

2016-09-27 23:05 UTC, bhuvan-rk commented on service/src/test/java/com/ge/predix/acs/privilege/management/dao/GraphResourceRepositoryTest.java
> +        assertThat(IteratorUtils.count(this.graph.vertices()), equalTo(2L));
@sanjeevchopra 
Think we need to add assertion that checkVersionVertexExists(2) returns false before creation and returns true after being created.

2016-09-27 23:05 UTC, bhuvan-rk requested changes
@sanjeevchopra 
Done reviewing.

2016-09-27 23:10 UTC, sanjeevchopra commented on service/src/test/java/com/ge/predix/acs/privilege/management/dao/GraphResourceRepositoryTest.java
> +        assertThat(IteratorUtils.count(this.graph.vertices()), equalTo(2L));
@bhuvan-rk this is testing that a new vertex is added. the exists test is being done with version 1.  Though, a exists == false check should be added before version 1 is created.

2016-09-27 23:36 UTC, DarioAmiri approved these changes
I found minor issues to consider addressing in a future story.

2016-09-27 23:36 UTC, amiri-ge commented on service/src/main/java/com/ge/predix/acs/config/GraphConfig.java
> +                new String[] { ZONE_ID_KEY, SUBJECT_ID_KEY });
nitpick: why is the formatting of this call to createUniqueCompositeIndex different than the one before? Are we using the eclipse formatting rules for this project?

2016-09-27 23:36 UTC, amiri-ge commented on service/src/main/java/com/ge/predix/acs/config/GraphConfig.java
> +            final String[] propertyKeyNames, final Class<?> propertyKeyType) throws InterruptedException {
This method signature assumes that all property keys of the composite index are the same type. Will this always be the case? Does it make sense to provide property (keyName, keyType) tuples instead?

2016-09-28 00:04 UTC, sanjeevchopra reviewed
@amiri-ge @bhuvan-rk 
Addressed your comments and removed  redundant graph setup in tests.

2016-09-28 00:04 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/config/GraphConfig.java
> +            final String[] propertyKeyNames, final Class<?> propertyKeyType) throws InterruptedException {
yes, we can add that when we have that use case.

2016-09-28 00:04 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/config/GraphConfig.java
> +                new String[] { ZONE_ID_KEY, SUBJECT_ID_KEY });
fixed

2016-09-28 00:09 UTC, merged