Decision caching changes needed for policy evaluation + controller test changes
predix/acs pull request #49
Opened 2016-10-04 18:04 UTC by bhuvan-rk

2016-10-04 18:04 UTC, bhuvan-rk commented
@sanjeevchopra Please review PR.

2016-10-04 22:46 UTC, sanjeevchopra requested changes

2016-10-04 22:46 UTC, sanjeevchopra commented on acs-integration-tests/src/test/java/com/ge/predix/integration/test/PolicyEvaluationCachingIT.java
> +        // test with empty policy set evaluation order list
empty v/s null should be covered in unit tests

2016-10-04 22:46 UTC, sanjeevchopra commented on acs-integration-tests/src/test/java/com/ge/predix/integration/test/PolicyEvaluationCachingIT.java
> +        // test with the policy set evaluation order reversed
this and the previous test both test the same thing i.e. policySetIds are evaluated in a specified order

2016-10-04 22:46 UTC, sanjeevchopra commented on acs-integration-tests/src/test/java/com/ge/predix/integration/test/PolicyEvaluationCachingIT.java
> +    public void testPolicyEvalCacheWithMultiplePolicySets() throws Exception {
please limit this to one evaluation with 2 policysets, change one policySet and confirm that the eval result changes.  (cached decision is not used)

2016-10-04 22:46 UTC, sanjeevchopra commented on acs-integration-tests/src/test/java/com/ge/predix/integration/test/PolicyEvaluationCachingIT.java
> +    public void testPolicyEvalCacheWhenResourceChanges() throws Exception {
pls limit to one usecase:  attributes change on resource , assert that eval result changes accordingly. If other combinations of this test are missing , they should be tested in unit/controller tests.

2016-10-04 22:46 UTC, sanjeevchopra commented on acs-integration-tests/src/test/java/com/ge/predix/integration/test/PolicyEvaluationCachingIT.java
> +        this.policyHelper.setTestPolicy(this.acsAdminRestTemplate, this.acsZone1Headers, endpoint, policyFile);
line 352:  pls move this test as a unit test : onBatchUpdate  assertThat cache timestamps get updated for all resources

2016-10-04 22:46 UTC, sanjeevchopra commented on acs-integration-tests/src/test/java/com/ge/predix/integration/test/PolicyEvaluationCachingIT.java
>      public void testPolicyEvalCacheWhenSubjectChanges() throws Exception {
same comments as resource test

2016-10-04 22:46 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/service/policy/evaluation/PolicyEvaluationServiceImpl.java
>      public PolicyEvaluationResult evalPolicy(final PolicyEvaluationRequestV1 request) {
not part of this story: service class should not have any knowledge/dependency on REST request payload (which is a public API)

2016-10-04 22:46 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/service/policy/evaluation/PolicyEvaluationServiceImpl.java
> +        List<PolicySet> filteredPolicySets = filterPolicySetsByPriority(subjectIdentifier, uri, allPolicySets,
not part of this story:
Maybe we need another internal type (PolicyEvaluationInput ?) which is prepared after validation and filtering. 
- move all validation and filtering logic in a different class
- this will also remove the need for the if/else on line 112 for building the key

2016-10-05 00:22 UTC, bhuvan-rk commented on acs-integration-tests/src/test/java/com/ge/predix/integration/test/PolicyEvaluationCachingIT.java
> +        this.policyHelper.setTestPolicy(this.acsAdminRestTemplate, this.acsZone1Headers, endpoint, policyFile);
This unit test already exists. So I'll just remove the IT. Ditto for Subjects as well.

2016-10-05 00:29 UTC, bhuvan-rk commented on service/src/main/java/com/ge/predix/acs/service/policy/evaluation/PolicyEvaluationServiceImpl.java
>      public PolicyEvaluationResult evalPolicy(final PolicyEvaluationRequestV1 request) {
I've created a new user-story to track these comments : 

https://rally1.rallydev.com/#/59288076735d/detail/userstory/67067764948

2016-10-05 00:30 UTC, bhuvan-rk commented on service/src/main/java/com/ge/predix/acs/service/policy/evaluation/PolicyEvaluationServiceImpl.java
> +        List<PolicySet> filteredPolicySets = filterPolicySetsByPriority(subjectIdentifier, uri, allPolicySets,
Refer to comments above, separate user story created. 

https://rally1.rallydev.com/#/59288076735d/detail/userstory/67067764948

2016-10-05 20:35 UTC, bhuvan-rk commented
http://predix1.jenkins.build.ge.com/job/Predix-Security/job/acs-build-n-test-pullrequest/667/

JENKINS build PASSED

2016-10-05 20:36 UTC, bhuvan-rk commented
@sanjeevchopra I'll merge to multiple_policy_sets and then fix the conflicts if any

2016-10-05 22:20 UTC, merged