US45006: Make subject attributes consistent
predix/acs pull request #53
Opened 2016-10-08 00:24 UTC by matiasa123

- Modified PolicyEvaluationRequestV1Test.java to reflect Set is unordered
- Modified PolicyEvaluationRequestV1 so that subjectAttributes and resourceAttributes are sets instead of list
- Modified PolicyEvaluationRequestV1 so that functions reflect Subject/ResourceAttributes are sets instead of list
- Modified Unit tests that failed to compile due to the changes to PolicyEval
- Modified Integration tests to reflect new changes

2016-10-08 00:30 UTC, DarioAmiri requested changes
Clean up the import I pointed out. Everything else looks good.

2016-10-08 00:30 UTC, DarioAmiri commented on acs-integration-tests/src/test/java/com/ge/predix/test/utils/PolicyHelper.java
> +import java.util.*;
Wildcard imports are considered a bad practice please be explicit.

2016-10-08 00:56 UTC, matiasa123 commented
http://predix1.jenkins.build.ge.com/job/Predix-Security/job/acs-build-n-test-pullrequest/670/console
Recording test results
Recording fingerprints
Notifying upstream projects of job completion
Finished: SUCCESS

2016-10-08 01:01 UTC, matiasa123 commented
Fixed thanks for catching that

2016-10-08 01:10 UTC, DarioAmiri requested changes

2016-10-08 01:10 UTC, DarioAmiri commented on model/src/main/java/com/ge/predix/acs/rest/PolicyEvaluationRequestV1.java
> +                equalsBuilder.append(this.subjectAttributes, other.subjectAttributes);
I don't believe this is the equivalent of comparing all items for equality. HashSet.equals() does not call equals() for every item in the set. See See https://docs.oracle.com/javase/7/docs/api/java/util/Set.html

2016-10-10 18:02 UTC, matiasa123 commented on model/src/main/java/com/ge/predix/acs/rest/PolicyEvaluationRequestV1.java
> +                equalsBuilder.append(this.subjectAttributes, other.subjectAttributes);
I can see where your concerns come from.  At first I was hesitant to use the built in equals operation with set.  My thinking is it would be wise to use the built in equals because we can't control what kind of set our users are loading into PolicyEvalRequest and there may be equals criteria outside of matching type, size, and elements.  

Also it is important to point out that depending on the set our user uses we may not have any guarantee's with how the set is ordered (http://www.programcreek.com/2013/03/hashset-vs-treeset-vs-linkedhashset/).  This is my primary concern with implementing element by element comparison in our function especially considering we are seeing alot of HashSets.   

According to HashSets documents equals is inherited from AbstractSet
https://docs.oracle.com/javase/7/docs/api/java/util/HashSet.html

AbstractSet equals checks type, set size, and then each individual element.
Documentation says
This implementation first checks if the specified object is this set; if so it returns true. Then, it checks if the specified object is a set whose size is identical to the size of this set; if not, it returns false. If so, it returns containsAll((Collection) o).
https://docs.oracle.com/javase/7/docs/api/java/util/AbstractSet.html#equals(java.lang.Object)

2016-10-10 18:24 UTC, matiasa123 commented on model/src/main/java/com/ge/predix/acs/rest/PolicyEvaluationRequestV1.java
> +                equalsBuilder.append(this.subjectAttributes, other.subjectAttributes);
Offline we discussed this and  @DarioAmiri agreed but requested that comments be added for anyone who runs into this line of code later.

2016-10-10 18:29 UTC, DarioAmiri approved these changes

2016-10-10 18:29 UTC, merged