US77587: Added attribute reader and adapter for in-memory attribute s…
predix/acs pull request #91
Opened 2017-02-23 22:57 UTC by irinaepshteyn

…tore.

2017-02-23 23:11 UTC, irinaepshteyn commented
All tests PASSED: 
https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-build-pullrequest/47/

2017-02-24 00:21 UTC, FrankGasparovic requested changes

2017-02-24 00:21 UTC, FrankGasparovic commented on service/src/main/java/com/ge/predix/acs/attribute/connectors/ZoneConfiguration.java
> +    package com.ge.predix.acs.attribute.connectors;
Remove extra space

2017-02-24 00:21 UTC, FrankGasparovic commented on service/src/main/java/com/ge/predix/acs/attribute/connectors/ZoneConfiguration.java
> +    private AttributeReader resourceAttributeReader;
No setters or getters and also not wiring the bean, how will we use the resourceAttributeReader?

2017-02-24 00:21 UTC, FrankGasparovic commented on service/src/main/java/com/ge/predix/acs/attribute/connectors/ZoneConfiguration.java
> +    public AttributeReader getResourceAttributeReader(final String zoneId) {
Is this zoneId as an argument a stub for when we will lookup the which attributeReader to use from the persistent store?

2017-02-24 00:34 UTC, irinaepshteyn commented on service/src/main/java/com/ge/predix/acs/attribute/connectors/ZoneConfiguration.java
> +    private AttributeReader resourceAttributeReader;
The idea is to construct resourceAttributeReader based on zone configuration read from the database.

2017-02-24 00:36 UTC, irinaepshteyn commented on service/src/main/java/com/ge/predix/acs/attribute/connectors/ZoneConfiguration.java
> +    public AttributeReader getResourceAttributeReader(final String zoneId) {
When we are ready to persist zone configuration, zoneId will be used to read zone configuration from the database

2017-02-24 05:05 UTC, sanjeevchopra requested changes

2017-02-24 05:05 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/service/policy/evaluation/PolicyEvaluationServiceImpl.java
> +    @Autowired
ZoneConfiguration or ZoneId can be directly loaded from spring authentication, This will avoid any changes to higher layers and pushing this info downstream.
 `((ZoneOAuth2Authentication) SecurityContextHolder.getContext().getAuthentication()).getZoneId()`

2017-02-24 05:05 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/attribute/connectors/InMemoryAttributeStore.java
> +public class InMemoryAttributeStore {
This class is unnecessary - InMemoryStoreAdapter can simply hold a map within it.

2017-02-24 05:05 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/attribute/connectors/InMemoryAttributeStoreAdapter.java
> +public class InMemoryAttributeStoreAdapter implements AttributeStoreAdapter {
In hindsight, because the adapter really belongs outside ACS, this story should just have the initial CustomResourceAttributeReader return a fixed set of attributes.  (Or the policy evaluation test can mock the attributeReader)
The key part of this story is the Evaluation test you, wrote and changes in evaluation code path to use a CustomResourceAttributeReader

2017-02-24 05:05 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/attribute/connectors/CustomResourceAttributeReader.java
> +public class CustomResourceAttributeReader implements AttributeReader {
more thoughts on naming :) 
AttributeReader is how its consumers use it. The classes which implement them can be different things. e.g. 
* `ResourceAttributeConnector implements AttributeReader` 
* `PrivilegeManagementServiceImpl implements PrivilegeManagementService, AttributeReader, SubjectAttributeReader`  (this also means we can get rid of DefaultSubjectAttributeReader and DefaultResourceAttributeReader)

2017-02-24 05:05 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/attribute/connectors/ZoneConfiguration.java
> +public class ZoneConfiguration {
Configuration will be fleshed out in the next story - most likely these 2 fields will become part of ZoneEntity class, and link to a ConnectorConfiguration JPAEntity.

2017-02-24 17:01 UTC, anubhavi25 requested changes

2017-02-24 17:01 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/attribute/connectors/AttributeReader.java
> +    Set<Attribute> getAttributes(final String identifier);
Concrete classes implementing interface methods should declare the parameters as `final` so this is a redundant use of it. This is also supposed to be enforced by our CheckStyle rules via the `RedundantModifier` module but it's not due to a bug in the version of CheckStyle we're using. I've updated to the latest version of CheckStyle on the `develop` branch so please rebase this branch onto `develop` and rebuild; once you do so you'll see this issue being flagged properly.

2017-02-24 17:01 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/attribute/connectors/AttributeStoreAdapter.java
> +    Set<Attribute> getAttributes(final String identifier);
See comment re. redundant use of final in interface methods

2017-02-24 17:01 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/attribute/connectors/SubjectAttributeReader.java
> +    Set<Attribute> getAttributesByScope(final String identifier, final Set<Attribute> scopes);
See comment re. redundant use of final in interface methods

2017-02-27 17:04 UTC, anubhavi25 approved these changes

2017-02-27 17:18 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/attribute/connectors/ResourceAttributeReader.java
> +public interface ResourceAttributeReader extends AttributeReader {
Do we anticipate adding more functionality to this interface in the immediate future?

If so, maybe put a comment saying that it shouldn't be refactored out?

If not, should we delete this interface and replace `implements ResourceAttributeReader` with `implements AttributeReader` everywhere?

2017-02-27 17:26 UTC, irinaepshteyn commented on service/src/main/java/com/ge/predix/acs/attribute/connectors/ResourceAttributeReader.java
> +public interface ResourceAttributeReader extends AttributeReader {
Decided to be explicit for code readability

2017-02-28 02:13 UTC, sanjeevchopra approved these changes
@irinaepshteyn  this branch is ready for merge, imo. please review.

2017-02-28 19:11 UTC, merged