US87160: In-memory and Redis cache integration for resource attribute…
predix/acs pull request #93
Opened 2017-03-02 00:15 UTC by anubhavi25

… connector

Signed-off-by: Frank <frank.gasparovic@ge.com>

2017-03-02 17:37 UTC, FrankGasparovic reviewed
Looks good

2017-03-02 17:37 UTC, FrankGasparovic commented on acs-integration-tests/pom.xml
>                              <excludes>
Add ACSMetering until we figure out how to fix that test?

2017-03-02 17:37 UTC, FrankGasparovic commented on acs-integration-tests/src/test/java/com/ge/predix/integration/test/ExternalResourceAttributeReaderIT.java
> +    private static final String ASSET_ATTRIBUTES_JSON =
Store JSON in src/test/resources like we do for other integration tests

2017-03-02 18:49 UTC, FrankGasparovic commented on service/src/test/java/com/ge/predix/acs/service/policy/evaluation/PolicyEvaluationWithAttributeConnectorTest.java
> +import com.ge.predix.acs.attribute.readers.ExternalSubjectAttributeReader;
Should we stick to calling everything connectors or readers? We have these ExternalResourceAttributeReader and ExternalSubjectAttributeReader, but the test is called

2017-03-02 21:38 UTC, irinaepshteyn requested changes
These are my initial comments.  I will continue reviewing...

2017-03-02 21:38 UTC, irinaepshteyn commented on acs-integration-tests/pom.xml
> +            <dependencies>
Since we added another profile, please update (or add a story to update) https://github.build.ge.com/predix/acs-ci-config/blob/master/AcsTestsReadme.md

2017-03-02 21:38 UTC, irinaepshteyn commented on acs-integration-tests/pom.xml
> +            <dependencies>
In the past it was decided to place test reports outside of target directory so reports are not removed by 'mvn clean' and retained by Jenkins for each profile.  Refer to reportsDirectory and summaryFile in the failsafe plugin configuration for, for example, public profile.
It might not be relevant any longer since each profile is run by the separate Jenkins job now.
We need to decide if we still want to maintain custom output directories and be consistent in every profile.

2017-03-02 21:38 UTC, irinaepshteyn commented on acs-integration-tests/pom.xml
>                              </excludes>
Since for acceptance profile we only execute single ACSAcceptanceIT test, excludes section is not needed.  Please remove the whole section.

2017-03-02 21:38 UTC, irinaepshteyn commented on service/src/main/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReader.java
> +        // TODO: Add an inline call to the Asset Adapter based on configuration
Could we change it to private?

2017-03-02 21:38 UTC, irinaepshteyn commented on service/src/main/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReader.java
> +        return ((ZoneOAuth2Authentication) SecurityContextHolder.getContext().getAuthentication()).getZoneId();
Could we change it to private?

2017-03-03 02:17 UTC, irinaepshteyn submitted a review, later dismissed
Additional review comments.

2017-03-03 02:17 UTC, irinaepshteyn commented on service/src/test/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReaderTest.java
> +
This test is written to test mostly InMemoryAttributeCache and not ExternalResourceAttributeReader.  It has to be renamed to com.ge.predix.acs.attribute.cache.InMemoryAttributeCacheTest.
For testing ExternalResourceAttributeReader it should be sufficient to mock cache to return no attributes and mock getAttributesFromAdapter to return a set of attributes and compare what's returned from actual getAttributes.

2017-03-03 02:17 UTC, irinaepshteyn commented on service/src/test/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReaderTest.java
> +            Assert.assertTrue(attributes.contains(cachedAttribute));
Instead of 'for' loop could use Assert.assertTrue(attributes.containsAll(cachedAttributes)) or Assert.assertEquals(attributes, cachedAttributes);

2017-03-03 02:17 UTC, irinaepshteyn commented on acs-integration-tests/src/test/java/com/ge/predix/integration/test/ExternalResourceAttributeReaderIT.java
> +}
We need to add another IT: PolicyEvalCachingWithExternalResourceAttributeReaderIT to assert that policy decision is reevaluated if attributes cache is expired and attributes are refreshed.

2017-03-03 02:26 UTC, sanjeevchopra submitted a review, later dismissed

2017-03-03 02:26 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/attribute/cache/AbstractAttributeCache.java
> +public abstract class AbstractAttributeCache implements AttributeCache {
* This class does not need to know the difference between subject of resource. Just (id, attributes)
* Both resource and subject connector will have one instance of each of this cache
* On that note most of the connector implementation will be subject/resource agnostic.

2017-03-03 02:26 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/attribute/cache/AttributeCache.java
> +public interface AttributeCache {
Dont see much value in this interface. Just make this the abstract class?

2017-03-03 02:26 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/attribute/cache/AbstractAttributeCache.java
> +    public abstract long getConfiguredTtl();
please add time unit to the method name

2017-03-03 02:26 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/attribute/cache/AbstractAttributeCache.java
> +    public abstract long getExpiration(String key);
please add time unit to the method name

2017-03-03 02:26 UTC, sanjeevchopra commented on service/pom.xml
> +        <dependency>
Please check with Anurag on process to get new dependencies approved.

2017-03-03 02:26 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReader.java
> +public class ExternalResourceAttributeReader implements ResourceAttributeReader {
`ExternalAttributeSourceReader` seems more accurate. I still like `ResourceAttributeConnector` , though :)

2017-03-03 02:26 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReader.java
> +    public Set<Attribute> getAttributesFromAdapter(final String zoneId, final String resourceId) {
getAttributesFromAdapters  (plural)

2017-03-03 02:26 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/policy/evaluation/cache/AbstractPolicyEvaluationCache.java
> +import org.codehaus.jackson.map.ObjectMapper;
pls revert changes to this package

2017-03-03 02:26 UTC, sanjeevchopra commented on service/src/test/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReaderTest.java
> +        for (Attribute cachedAttribute : cachedAttributes) {
use equals()

2017-03-03 02:26 UTC, sanjeevchopra commented on service/src/test/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReaderTest.java
> +        Set<Attribute> attributes = Collections.singleton(
expectedAttributes

2017-03-03 02:26 UTC, sanjeevchopra commented on service/src/test/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReaderTest.java
> +        Set<Attribute> cachedAttributes = this.externalResourceAttributeReader.getAttributes(RESOURCE_ID);
actualAttributes

2017-03-03 02:26 UTC, sanjeevchopra commented on service/src/test/java/com/ge/predix/acs/service/policy/evaluation/PolicyEvaluationWithAttributeConnectorTest.java
> +import com.ge.predix.acs.attribute.readers.ExternalSubjectAttributeReader;
point taken, @FrankGasparovic lets discuss naming tomorrow.

2017-03-03 22:33 UTC, sanjeevchopra commented on service/src/main/java/com/ge/predix/acs/attribute/cache/AbstractAttributeCache.java
> +public abstract class AbstractAttributeCache implements AttributeCache {
Discussed this with @anubhavi25 .  Added notes in redis caching story. 
* this pull request will be limited to in-memory caching only
* initially a common cache across zones is ok, however we need to enforce a max storage (at least max entries) on it
* key should be zone+id.   One cache each for attribute and subject connectors.

2017-03-06 17:36 UTC, anubhavi25 commented on acs-integration-tests/pom.xml
>                              <excludes>
Was added as part of DE22023

2017-03-06 17:36 UTC, anubhavi25 commented on acs-integration-tests/src/test/java/com/ge/predix/integration/test/ExternalResourceAttributeReaderIT.java
> +    private static final String ASSET_ATTRIBUTES_JSON =
Done

2017-03-06 17:38 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/service/policy/evaluation/PolicyEvaluationWithAttributeConnectorTest.java
> +import com.ge.predix.acs.attribute.readers.ExternalSubjectAttributeReader;
As discussed, we're sticking to the `Reader` suffix for connector-related internal abstractions and the `Connector` suffix for external abstractions

2017-03-06 17:41 UTC, anubhavi25 commented on acs-integration-tests/pom.xml
> +            <dependencies>
Added changes to `AcsTestsReadme.md` in the master branch of the acs-ci-config Git repo. Also these changes to add the `redis` Maven profile have been pulled out to another branch but when I re-introduce it I'll look into how to standardize the test output directories.

2017-03-06 17:41 UTC, anubhavi25 commented on acs-integration-tests/pom.xml
>                              </excludes>
Done

2017-03-06 17:42 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReader.java
> +        // TODO: Add an inline call to the Asset Adapter based on configuration
Made it package-private to allow testing

2017-03-06 17:42 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReader.java
> +        return ((ZoneOAuth2Authentication) SecurityContextHolder.getContext().getAuthentication()).getZoneId();
Made it package-private to allow testing

2017-03-06 17:42 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReaderTest.java
> +
Done

2017-03-06 17:42 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReaderTest.java
> +            Assert.assertTrue(attributes.contains(cachedAttribute));
Done

2017-03-06 17:42 UTC, anubhavi25 commented on acs-integration-tests/src/test/java/com/ge/predix/integration/test/ExternalResourceAttributeReaderIT.java
> +}
This will be added as part of US87156

2017-03-06 17:44 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/attribute/cache/AbstractAttributeCache.java
> +public abstract class AbstractAttributeCache implements AttributeCache {
Done. We can make the relevant config changes to bump up the app memory in acs-ci-config as part of US87168. Also, as discussed, Redis-related changes will be pulled out to the US87168 branch.

2017-03-06 17:58 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/attribute/cache/AbstractAttributeCache.java
> +    public abstract long getExpiration(String key);
Done (renamed this to `getRemainingTtlInSeconds`)

2017-03-06 17:58 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/attribute/cache/AbstractAttributeCache.java
> +    public abstract long getConfiguredTtl();
Done

2017-03-06 17:58 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/attribute/cache/AttributeCache.java
> +public interface AttributeCache {
Removed in lieu of `AbstractAttributeCache`

2017-03-06 17:59 UTC, anubhavi25 commented on service/pom.xml
> +        <dependency>
Now using EhCache which, according to Anurag, is under Apache licensing

2017-03-06 17:59 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReader.java
> +public class ExternalResourceAttributeReader implements ResourceAttributeReader {
As discussed, sticking to `ExternalResourceAttributeReader`

2017-03-06 17:59 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReader.java
> +    public Set<Attribute> getAttributesFromAdapter(final String zoneId, final String resourceId) {
Done

2017-03-06 17:59 UTC, anubhavi25 commented on service/src/main/java/com/ge/predix/acs/policy/evaluation/cache/AbstractPolicyEvaluationCache.java
> +import org.codehaus.jackson.map.ObjectMapper;
Done

2017-03-06 18:04 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReaderTest.java
> +        Set<Attribute> attributes = Collections.singleton(
Done

2017-03-06 18:05 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReaderTest.java
> +        Set<Attribute> cachedAttributes = this.externalResourceAttributeReader.getAttributes(RESOURCE_ID);
Done

2017-03-06 18:05 UTC, anubhavi25 commented on service/src/test/java/com/ge/predix/acs/attribute/readers/ExternalResourceAttributeReaderTest.java
> +        for (Attribute cachedAttribute : cachedAttributes) {
Done

2017-03-06 18:16 UTC, anubhavi25 commented
@sanjeevchopra @irinaepshteyn please review again as there were non-trivial changes in the last commit (i.e. removed Redis-related changes, moved to EhCache and incorporated cache-related constraints)

2017-03-07 00:18 UTC, merged